import { StyleSheet } from 'react-native';

export const settingsStyles = StyleSheet.create({
	container: {
		flex: 1,
		padding: 16,
		backgroundColor: '#f5f5f5',
	},
	title: {
		fontSize: 24,
		fontWeight: 'bold',
		marginBottom: 16,
	},
	card: {
		backgroundColor: 'white',
		borderRadius: 8,
		padding: 16,
		marginBottom: 16,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	cardTitle: {
		fontSize: 18,
		fontWeight: 'bold',
		marginBottom: 8,
	},
	cardDescription: {
		fontSize: 14,
		color: '#666',
		marginBottom: 16,
	},
	row: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 16,
	},
	picker: {
		height: 50,
		width: 150,
		marginVertical: 8,
	},
	saveButton: {
		backgroundColor: '#007bff',
		padding: 16,
		borderRadius: 8,
		alignItems: 'center',
		marginTop: 16,
		marginBottom: 24,
		height: 56,
		justifyContent: 'center',
	},
	buttonDanger: {
		backgroundColor: '#dc3545',
		padding: 12,
		borderRadius: 8,
		alignItems: 'center',
		height: 48,
		justifyContent: 'center',
	},
	buttonOutline: {
		borderColor: '#007bff',
		borderWidth: 1,
		padding: 12,
		borderRadius: 8,
		alignItems: 'center',
		height: 48,
		justifyContent: 'center',
	},
	buttonText: {
		color: 'white',
		fontWeight: 'bold',
		fontSize: 16,
	},
	buttonOutlineText: {
		color: '#007bff',
		fontWeight: 'bold',
		fontSize: 16,
	},
	input: {
		height: 40,
		width: 100,
		borderWidth: 1,
		padding: 10,
		borderRadius: 4,
	},
	buttonRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginTop: 16,
		marginBottom: 8,
	},
	exportContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		marginTop: 8,
	},
	exportPicker: {
		height: 50,
		flex: 1,
	},
	exportButton: {
		padding: 12,
		borderRadius: 8,
		marginLeft: 8,
		height: 48,
		justifyContent: 'center',
		alignItems: 'center',
		width: 100,
	}
});
